---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:1.0.0-280'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8:1.2.0-23'
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-cv'

ansible_config: './ansible.cfg'

dependencies:
  galaxy: ./requirements.yml
#  python: ./requirements.txt
  system: ./bindep.txt

additional_build_steps:
  prepend: |
    RUN Ansible Builder prepend section
    RUN ls -lR
    RUN ls -l /
  append:
    - RUN echo This is a post-install command!
    - RUN ls -lR /runner
    - RUN ls -lR /dev
    - RUN ls -lR /tmp
