---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:1.0.0-280'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8:1.2.0-23'
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-cv'

ansible_config: './ansible.cfg'

dependencies:
  galaxy: ./requirements.yml
#  python: ./requirements.txt
  system: ./bindep.txt

additional_build_steps:
  prepend: |
    RUN echo Ansible Builder prepend section
    RUN pwd
    RUN echo $HOME
    RUN ls -lR /home/runner
    RUN ls -lR /runner
    RUN ls -lR /tmp
    RUN ls -l /
  append:
    - RUN echo This is a post-install command!
    - COPY qemu-img-7.0.0-13.el9_1.2.x86_64.rpm /home/runner/qemu-img-7.0.0-13.el9_1.2.x86_64.rpm
    - COPY qemu-img-7.0.0-13.el9_1.2.x86_64.rpm /tmp/qemu-img-7.0.0-13.el9_1.2.x86_64.rpm
    - RUN ls -lR /runner
    - RUN ls -lR /home/runner
    - RUN ls -lR /remote-source
    - RUN ls -lR /home
    - RUN ls -lR /root
    # expected error below
    - COPY qemdasfu-iasdgmg-7.0.0-13.el9_1.2.x86_64.rpm /root/qemu-img-7.0.0-13.el9_1.2.x86_64.rpm
