---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:1.0.0-280'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8:1.2.0-23'
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-cv'

ansible_config: './ansible.cfg'

dependencies:
  galaxy: ./requirements.yml
  python: ./requirements.txt
  system: ./bindep.txt

additional_build_steps:
  prepend: |
    RUN echo Ansible Builder prepend section
    RUN echo $HOME
    RUN ls -lR $HOME
  append:
    - RUN echo This is a post-install command!
    - RUN echo list installed ansible collections.
#    - RUN find /usr/share/ansible/collections/ansible_collections/ -type d -maxdepth 2
    - RUN find /usr/share/ansible/collections/ansible_collections/ -type d -name *.info
    - RUN echo list installed pip packages.
    - RUN pip3 list
    - RUN echo list installed rpm packages.
    - RUN rpm -qa | sort
    - RUN whoami
    - RUN pip3 show cx_Oracle
